name: Commit Message Lint

on:
  pull_request_target:
    types: [opened, synchronize, edited, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Validate commit messages against template
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Fetch commits in PR (first page up to 250 commits)
            const { data: commits } = await github.rest.pulls.listCommits({
              owner,
              repo,
              pull_number: prNumber,
              per_page: 250
            });

            const firstLine = (message) => (message || '').split('\n')[0];

            // Allowed patterns
            const chapterPattern = /^\[\d+장\]\s.+\s-\s.+$/;         // e.g. "[2장] 타입 - 정해인"
            const docsPattern = /^\[docs\]\s.+$/i;                      // e.g. "[docs] README 수정"

            const violations = [];
            for (const c of commits) {
              const msg = firstLine(c.commit && c.commit.message);
              // Skip merge commits or bot-generated commits if needed
              const isMerge = msg.startsWith('Merge ');
              const isBot = (c.author && c.author.type === 'Bot');
              if (isMerge || isBot) continue;

              const ok = chapterPattern.test(msg) || docsPattern.test(msg);
              if (!ok) {
                violations.push(`"${msg}"`);
              }
            }

            if (violations.length > 0) {
              core.setFailed(
                `커밋 메시지 템플릿 위반 ${violations.length}건:\n` +
                violations.map(v => `- ${v}`).join('\n') +
                `\n\n허용 형식 예:\n` +
                `- [2장] 타입 - 정해인\n` +
                `- [docs] README 수정\n`
              );
            } else {
              core.info('All commit messages comply with the required template.');
            }


